services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # tu accéderas à l'app sur http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    container_name: react_vite_app
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
